// <auto-generated />
using System;
using Communications.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Communications.API.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20190822110956_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Communications.API.Models.Domain.MailTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<string>("ClientId");

                    b.Property<string>("From");

                    b.Property<bool>("Processed");

                    b.Property<DateTime?>("ProcessedTimestamp");

                    b.Property<DateTime>("ReceivedTimestamp");

                    b.Property<string>("Subject");

                    b.Property<string>("To");

                    b.Property<Guid>("VendorId");

                    b.HasKey("Id");

                    b.ToTable("MailTasks");
                });

            modelBuilder.Entity("Communications.API.Models.Domain.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("DefaultFromAddress");

                    b.Property<string>("Name");

                    b.Property<DateTime>("RegisteredTimestamp");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
